<a href="https://colab.research.google.com/github/vit050587/Practical-case-Data-Science/blob/master/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Импорт библиотек

In [ ]:
!pip install folium==0.12.1

In [ ]:
import pandas as pd
import numpy as np
import folium
from sklearn import linear_model

<img src='https://drive.google.com/uc?export=view&id=1q1pSMnZVVhVeE9l2zGckBCF33BS2vKBd'>

# Загрузка данных

In [ ]:
!wget 'https://drive.google.com/uc?export=dowload&id=1oRtvvrVUoep5nnSexngfNFEB4cin5Rsa' -O final.csv

--2021-08-24 19:49:23--  https://drive.google.com/uc?export=dowload&id=1oRtvvrVUoep5nnSexngfNFEB4cin5Rsa
Resolving drive.google.com (drive.google.com)... 74.125.204.113, 74.125.204.102, 74.125.204.139, ...
Connecting to drive.google.com (drive.google.com)|74.125.204.113|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://doc-0s-c0-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/n586r3jgcc98u5iqch9rt58a9qirteod/1629834525000/14904333240138417226/*/1oRtvvrVUoep5nnSexngfNFEB4cin5Rsa?e=dowload [following]
--2021-08-24 19:49:25--  https://doc-0s-c0-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/n586r3jgcc98u5iqch9rt58a9qirteod/1629834525000/14904333240138417226/*/1oRtvvrVUoep5nnSexngfNFEB4cin5Rsa?e=dowload
Resolving doc-0s-c0-docs.googleusercontent.com (doc-0s-c0-docs.googleusercontent.com)... 74.125.203.132, 2404:6800:4008:c03::84
Connecting to doc-0s-c0-docs.googleusercontent.com (doc-0s-c0

In [ ]:
df = pd.read_csv('/content/final.csv')

In [ ]:
df

store  dayofweek        date  sales  ...  open  promo        lat        lon
0            1          3  2018-01-01   5530  ...     1      0  55.682829  37.416212
1            2          3  2018-01-01   4422  ...     1      0  55.686410  37.415503
2            3          3  2018-01-01   6823  ...     1      0  55.885081  37.476452
3            4          3  2018-01-01   9941  ...     1      0  55.711356  37.389027
4            5          3  2018-01-01   4253  ...     1      0  55.902867  37.609132
...        ...        ...         ...    ...  ...   ...    ...        ...        ...
1016090   1111          5  2020-07-29   5723  ...     1      1  55.878577  37.706292
1016091   1112          5  2020-07-29   9626  ...     1      1  55.791374  37.823187
1016092   1113          5  2020-07-29   7289  ...     1      1  55.756921  37.824353
1016093   1114          5  2020-07-29  27508  ...     1      1  55.798922  37.822139
1016094   1115          5  2020-07-29   8680  ...     1      1  55.582867  37.653329

[1016095 rows x 9 columns]

- store - магазин
- dayofweek - день недели
- date - дата
- sales - продажи
- customers - клиенты
- open - открыт магазин или нет
- promo - была ли промо акция
- lat - широта
- lon - долгота

# Делаем прогноз на июль 2020 года

<img src='https://drive.google.com/uc?export=view&id=1lkMiS2f-f-DwrBkEQIEp3HBxKm2Im9zX'>

In [ ]:
df_train = df[df['date'] < '2020-07-01']
df_test = df[df['date'] >= '2020-07-01']

In [ ]:
df_train

store  dayofweek        date  sales  ...  open  promo        lat        lon
0           1          3  2018-01-01   5530  ...     1      0  55.682829  37.416212
1           2          3  2018-01-01   4422  ...     1      0  55.686410  37.415503
2           3          3  2018-01-01   6823  ...     1      0  55.885081  37.476452
3           4          3  2018-01-01   9941  ...     1      0  55.711356  37.389027
4           5          3  2018-01-01   4253  ...     1      0  55.902867  37.609132
...       ...        ...         ...    ...  ...   ...    ...        ...        ...
983755   1111          4  2020-06-30   3945  ...     1      1  55.878577  37.706292
983756   1112          4  2020-06-30   7447  ...     1      1  55.791374  37.823187
983757   1113          4  2020-06-30   7932  ...     1      1  55.756921  37.824353
983758   1114          4  2020-06-30  24898  ...     1      1  55.798922  37.822139
983759   1115          4  2020-06-30   6858  ...     1      1  55.582867  37.653329

[983760 rows x 9 columns]

In [ ]:
df_test

store  dayofweek        date  sales  ...  open  promo        lat        lon
983760       1          5  2020-07-01   4665  ...     1      1  55.682829  37.416212
983761       2          5  2020-07-01   4838  ...     1      1  55.686410  37.415503
983762       3          5  2020-07-01   8149  ...     1      1  55.885081  37.476452
983763       4          5  2020-07-01  11543  ...     1      1  55.711356  37.389027
983764       5          5  2020-07-01   4475  ...     1      1  55.902867  37.609132
...        ...        ...         ...    ...  ...   ...    ...        ...        ...
1016090   1111          5  2020-07-29   5723  ...     1      1  55.878577  37.706292
1016091   1112          5  2020-07-29   9626  ...     1      1  55.791374  37.823187
1016092   1113          5  2020-07-29   7289  ...     1      1  55.756921  37.824353
1016093   1114          5  2020-07-29  27508  ...     1      1  55.798922  37.822139
1016094   1115          5  2020-07-29   8680  ...     1      1  55.582867  37.653329

[32335 rows x 9 columns]

# Возьмем несколько признаков

In [ ]:
features = [
    'store',
    'dayofweek',
    'customers',
    'open',
    'promo',
]

target = ['sales']

# Воспользуемся простым методом прогноза

<img src='https://drive.google.com/uc?export=view&id=1alUGHx-Pabz3C3xvFDHxYbgP3tsPsH1D'>

In [ ]:
model = linear_model.LinearRegression()

# Научим нашу модель

In [ ]:
model.fit(
    X=df_train[features],
    y=df_train[target]
)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
coefs = model.coef_[0]
coefs

array([-1.51031308e-01, -5.55572871e+01,  6.07463705e+00,  1.67556349e+03,
        1.27110167e+03])

In [ ]:
intercept = model.intercept_
intercept

array([352.11911259])

In [ ]:
df_train[features].head(1)

store  dayofweek  customers  open  promo
0      1          3        668     1      0

In [ ]:
1 * coefs[0] + 3 * coefs[1] + 668 * coefs[2] + 1 * coefs[3] + 0 * coefs[4] + intercept

array([5918.71726263])

In [ ]:
model.predict(df_train[features].head(1))

array([[5918.71726263]])

In [ ]:
df_train[target].head(1)

sales
0   5530

# Сделаем прогноз

<img src='https://drive.google.com/uc?export=view&id=1YUyJxrl9ZLCGCJjSK1PvAm8IeHZU7brE'>

In [ ]:
pred = model.predict(
    X=df_test[features]
)

In [ ]:
pred

array([[ 6289.00153871],
       [ 9271.49730015],
       [ 7527.9254348 ],
       ...,
       [ 7226.63866794],
       [25602.26472027],
       [ 6120.75266178]])

In [ ]:
pd.DataFrame(pred, columns=['pred'])

pred
0       6289.001539
1       9271.497300
2       7527.925435
3      11494.512399
4       6221.576406
...             ...
32330   5416.698889
32331   7512.297641
32332   7226.638668
32333  25602.264720
32334   6120.752662

[32335 rows x 1 columns]

# Оценим точность прогноза

<img src='https://drive.google.com/uc?export=view&id=1LK0jRvKpxNar4OCCJI_XdqnYs8hxnIUU'>

In [ ]:
df_test['pred'] = pred

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
df_test[target + ['pred']]

sales          pred
983760    4665   6289.001539
983761    4838   9271.497300
983762    8149   7527.925435
983763   11543  11494.512399
983764    4475   6221.576406
...        ...           ...
1016090   5723   5416.698889
1016091   9626   7512.297641
1016092   7289   7226.638668
1016093  27508  25602.264720
1016094   8680   6120.752662

[32335 rows x 2 columns]

In [ ]:
df_test['sales'].sum() / df_test['pred'].sum()

1.0347025941635466

In [ ]:
df_test['sales'].sum()

194886651

In [ ]:
df_test['pred'].sum()

188350403.39059585

# GIS

In [ ]:
df_agg = df.groupby('store', as_index=False).mean()[['store', 'sales']]
df_agg.rename(columns={'sales': 'sales_average'}, inplace=True)
df_agg.sales_average = df_agg.sales_average.astype('int64')
df_agg

store  sales_average
0         1           3949
1         2           4127
2         3           5747
3         4           8030
4         5           3871
...     ...            ...
1110   1111           4347
1111   1112           8474
1112   1113           5522
1113   1114          17218
1114   1115           5230

[1115 rows x 2 columns]

In [ ]:
df_stores = df.merge(df_agg, on='store').drop_duplicates(subset='store')

In [ ]:
df_stores = df_stores[['store', 'lat', 'lon', 'sales_average']]

In [ ]:
df_stores

store        lat        lon  sales_average
0            1  55.682829  37.416212           3949
941          2  55.686410  37.415503           4127
1882         3  55.885081  37.476452           5747
2823         4  55.711356  37.389027           8030
3764         5  55.902867  37.609132           3871
...        ...        ...        ...            ...
1011390   1111  55.878577  37.706292           4347
1012331   1112  55.791374  37.823187           8474
1013272   1113  55.756921  37.824353           5522
1014213   1114  55.798922  37.822139          17218
1015154   1115  55.582867  37.653329           5230

[1115 rows x 4 columns]

In [ ]:
df_agg_train = df_stores[df_stores['store'] < 1111]
df_agg_test = df_stores[df_stores['store'] >= 1111]

In [ ]:
df_agg_train

store        lat        lon  sales_average
0            1  55.682829  37.416212           3949
941          2  55.686410  37.415503           4127
1882         3  55.885081  37.476452           5747
2823         4  55.711356  37.389027           8030
3764         5  55.902867  37.609132           3871
...        ...        ...        ...            ...
1007053   1106  55.894896  37.601787           4077
1007994   1107  55.713839  37.405167           5128
1008751   1108  55.755917  37.824296           4763
1009692   1109  55.891862  37.614217           4048
1010449   1110  55.707206  37.815763           3770

[1110 rows x 4 columns]

In [ ]:
df_agg_test

store        lat        lon  sales_average
1011390   1111  55.878577  37.706292           4347
1012331   1112  55.791374  37.823187           8474
1013272   1113  55.756921  37.824353           5522
1014213   1114  55.798922  37.822139          17218
1015154   1115  55.582867  37.653329           5230

In [ ]:
this_map = folium.Map(prefer_canvas=True)

def plotDot(point, color):
    
    folium.CircleMarker(
        location=[point.lat, point.lon],
        radius=2,
        weight=5,
        color=color,
        popup=point.sales_average
    ).add_to(this_map)
    
df_agg_train.apply(plotDot, axis=1, color='#3388FF')
df_agg_test.apply(plotDot, axis=1, color='#FF5A33')    

this_map.fit_bounds(this_map.get_bounds())

this_map

AttributeError: ignored